### ISSUE TITLE
Import stocks with NASDAQ Handelsplatz

### ISSUE THREAD

**Issue by stefan-enway** [codeofsumit/tresor-import#269]
hi, can i add stocks e.g. US88160R1014 (Tesla) traded at NASDAQ?
Also with a date and value in the past? I usually trade at the place of the company, sometimes also with less common exchanges (e.g. australia for all the lithium mining companies). Are non EUR stocks supported? (US$, Austrlian$, HK?)

**Comment by codeofsumit** [comment]
Hi @stefan-enway - this Repo is just about PDF parsing.
Please [use the community](https://community.tresor.one/) for questions like these.

Nonetheless I would like to answer it of course:

Non EUR stocks are supported. Tresor One will prefer EUR prices and use them whenever possible to avoid currency exchanges as prices become less precise. As the portfolios are currently all in EUR, there is no need in using NASDAQ stocks for Tesla when prices are available in EUR. I can see some usecases for this (e.g. different trading times) but we are restricting this at the moment.

If you add e.g. Pinterest as a holding, it's not listed in German exchanges so you will get NASDAQ/AMEX/NYSE prices for it (with currency conversion to EUR).
If you add other stocks that do not find a price yet it might be because we haven't added the exchange yet. If that's the case for you, report the ISIN in the community and we will take a look if we can add the exchange.

Cheers,
Sumit
