### ISSUE TITLE
Proper distributable

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#6]
Alright it's time for a proper distributable.

1. Tresor One abstracted the import so much so that it could be imported via npm
2. The imports here, e.g. `import { validateActivity } from @/helper` clash with the T1 codebase, because `@` is a different root level here and in the T1 codebase -> the solution would be to include compiled code
3. Less copy&pasting and much clearer which version of the import we use in T1

What's necessary to get a distributable?

- [ ] `npm build` script that creates a single `index.js` with the code
- [ ] Publish on npm (@codeofsumit will do that)
- [ ] Exported function to be importable like `import { extractActivities } from 'tresor-import'`

What else?

cc @dredav @felixheck @d-a-n

**Comment by dredav** [comment]
For that, we can also change the logic in the index.js file: Today we export the functions `extractActivities` and `extractCSVActivities`. Is it not better to export a function with a file parameter? This function can read the file through the FileReader and then handle the files different on e.g. file parameter file like the extension? This sounds quite easier to use, because we can add additional file formats without adjust the logik in tresor.one. This function will return 0..n activities.

**Comment by codeofsumit** [comment]
Agree 👍 👍
