### ISSUE TITLE
Ignore Splits from Portfolio Performance

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#97]
According to this user, Splits from PP are imported as "buys".
Let's ignore them instead as we handle splits centrally in T1

https://community.tresor.one/c/product-updates/aktiensplits-in-tresor-one#comment_175750

**Comment by dredav** [comment]
I think we can't handle this case at the import logic. The right place should be at the logic after the import, wich ensure that an equal activity does not exists. Here the activities from the sample:

**Activity before stock split:**
`[{"isin":"DE0005659700","wkn":"565970","type":"Buy","company":"ECKERT+ZIEGLER AG O.N.","symbol":"EUZ","date":"2020-07-01","shares":24,"amount":898.2,"grossAmount":0,"tax":0,"fee":0,"currency":"EUR","grossCurrency":"","exchangeRate":0,"price":37.425,"parsed":true,"filename":"onvista-after.csv0"}]`

**Activity after stock split:**
`[{"isin":"DE0005659700","wkn":"565970","type":"Buy","company":"ECKERT+ZIEGLER AG O.N.","symbol":"EUZ","date":"2020-07-01","shares":6,"amount":898.2,"grossAmount":0,"tax":0,"fee":0,"currency":"EUR","grossCurrency":"","exchangeRate":0,"price":149.7,"parsed":true,"filename":"onvista-before.csv0"}]`

**The diff:**
<img width="1052" alt="Screen Shot 2020-08-31 at 19 20 19" src="https://user-images.githubusercontent.com/731073/91747855-40671600-ebbf-11ea-9095-20e84b7878da.png">

**How to handle:**
For companies with stock splits the logic should ignore the price from both activities (due to rounding issues) or handle the equal comparison with minor tolerance. The amount of shares shoud be multiply the stock split factor.

**Comment by dredav** [comment]
@codeofsumit Can we close this issue / or will you "move" it to the core project? I think we can't handle this with the import logic.
